apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    apps: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: synergychat-crawler
  template:
    metadata:
      labels:
        apps: synergychat-crawler
    spec:
      containers:
        - name: synergychat-crawler
          image: bootdotdev/synergychat-crawler:latest
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap